# Frontend Dockerfile
# Build stage
FROM node:20-alpine AS build
WORKDIR /frontend
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install --legacy-peer-deps --silent
COPY frontend ./
RUN npm run build

# Production stage
FROM nginx:alpine AS prod
WORKDIR /usr/share/nginx/html
COPY --from=build /frontend/dist .
# remove default config and add minimal
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
